version: "3.3"

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=admin
      - REDIS_PORT=6379

  mongodb:
    image: mongo:6-jammy
    ports:
      - "27017:27017"
    volumes:
      - db_volume:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: casino
volumes:
  db_volume:
